# SPDX-FileCopyrightText: 2022 Sascha Brawer <sascha@brawer.ch>
# SPDX-License-Identifier: MIT

name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2

    - name: Check REUSE Compliance
      uses: fsfe/reuse-action@v1

    - name: Install Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.22.2

    - name: Build
      run: |
        go build -ldflags="-s -w" -v ./cmd/...

    - name: Test
      run: go test -v ./...
